version: '3'

services:
  kafka:
    image: lensesio/box:latest
    ports:
         - '3030:3030'
         - '9092:9092'
    env_file:
      - .env
    environment:
      - EULA=https://licenses.lenses.io/d/?id=${LENSESIO_KEY}
      - ADV_HOST=kafka
